Upfinancas.MVC/Controllers/PessoaController.cs
using System;
using AutoMapper;
using System.Collections.Generic;
using System.Web.Mvc;
using Upfinancas.MVC.Filters;
using Upfinancas.MVC.ViewModel;
using UpFinancas.App.Interfaces;
using UpFinancas.Domain.Entities;

namespace Upfinancas.MVC.Controllers
{
    [AutorizacaoFilter]
    public class PessoaController : Controller
    {
        private readonly IPessoaApp _app;

        public PessoaController(IPessoaApp app)
        {
            _app = app;
        }

        public ActionResult Index()
        {
            var  usuario = (int)Session["USUARIO"];
            var pessoas = _app.Listar(usuario);

            var pessoaViewModel = Mapper.Map<IEnumerable<Pessoa>, IEnumerable<PessoaViewModel>>(pessoas);
            return View(pessoaViewModel);
        }
        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(PessoaViewModel pessoaView)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var pessoa = Mapper.Map<PessoaViewModel, Pessoa>(pessoaView);
                    pessoa.UsuarioId = (int)Session["USUARIO"];
                    _app.Salvar(pessoa);
                    TempData["SUCESSO"] = "Pessoa salva com sucesso!";
                    return RedirectToAction("Index");

                }
                catch (Exception e)
                {
                    TempData["ERRO"] = "Erro ao salvar a pessoa: " + e.Message;
                    return View();
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Editar(int pessoaId)
        {
            try
            {
                var pessoa = _app.Buscar((int) Session["USUARIO"], pessoaId);
                var pessoaViewModel = Mapper.Map<Pessoa, PessoaViewModel>(pessoa);
                return View("Cadastrar", pessoaViewModel);

            }
            catch (Exception e)
            {
                TempData["ERRO"] = "Erro ao buscar a pessoa: " + e.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult AlterarStatus(int pessoaId)
        {
            try
            {
                _app.AlterarStatus(pessoaId,(int)Session["USUARIO"]);
                TempData["SUCESSO"] = "Pessoa atualizada com sucesso!";

                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                TempData["ERRO"] = "Erro ao atualizar a pessoa: " + e.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

Upfinancas.MVC/Views/Pessoa/Cadastrar.cshtml
@model Upfinancas.MVC.ViewModel.PessoaViewModel
@{
    ViewBag.Title = "Pessoas(fontes)";
}
<h3 class="page-title">
    Pessoas <small>fontes</small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Pessoa")">Pessoa</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            Nova Pessoa
        </li>
    </ul>

</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("Cadastrar", "Pessoa", FormMethod.Post, new { @id = "form1"}))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)
                    <div class="portlet box grey-cascade">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa  fa-plus"></i> Cadastrar nova fonte
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <div class="form-body form-vertical">
                                <div class="row">
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            Nome: <span class="text-danger">* </span>
                                        </label>
                                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            Telefone:
                                        </label>
                                        @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            Celular:
                                        </label>
                                        @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            E-mail:
                                        </label>
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            Rua:
                                        </label>
                                        @Html.EditorFor(model => model.Rua, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Rua, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            Número:
                                        </label>
                                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            Bairro:
                                        </label>
                                        @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                                    </div>
                                    <div class="col-md-3 col-sm-3 col-xs-12 form-group">
                                        <label>
                                            Cidade:
                                        </label>
                                        @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                                        <label>
                                            Complemento:
                                        </label>
                                        @Html.TextAreaFor(model => model.Complemento,  new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Complemento, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <button type="submit" class="btn green">Salvar</button>
                                        @Html.ActionLink("Volta", "Index", "Pessoa", null, new { @class = "btn default" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var Inside = function () {
        return {
            init: function () {
            }
        };
    }();
</script>

Upfinancas.MVC/Views/Pessoa/Index.cshtml
@model IEnumerable< Upfinancas.MVC.ViewModel.PessoaViewModel > 
@{
    ViewBag.Title = "Pessoas";
}
<h3 class="page-title">
    Pessoas <small>cadastradas</small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            Pessoas
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <a href="@Url.Action("Cadastrar","Pessoa")" class="btn green btn-fit-height"><i class="fa  fa-plus"></i> Novo</a>
        </div>
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN VALIDATION STATES-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-ticket"></i>Pessoas
                </div>
            </div>
            <div class="portlet-body ">
                <div class="row">
                    <div class="col-md-12">
                        @if (Model.Count() > 0)
                        {
                            <table class="table table-striped text-center" id="table-viewer">
                                <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Nome</th>
                                    <th>Dt. Criação</th>
                                    <th>Visualizar</th>
                                    <th>Status</th>
                                </tr>
                                </thead>
                                @foreach (var row in Model)
                                {
                                    <tr>
                                        <td>
                                            @row.Id
                                        </td>
                                        <td>
                                            @row.Nome
                                        </td>
                                        <td>
                                            @row.GetDataCadastroPtBr()
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Editar","Pessoa", new { pessoaId = row.Id })" class="btn green btn-xs" title="Visualizar"><i class="fa fa-search"></i></a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("AlterarStatus","Pessoa",new { pessoaId = row.Id })" class="btn @(row.GetStatus().Equals("Inativo") ? "green" : "red") btn-xs"><i class="fa @(row.GetStatus().Equals("Inativo") ? "fa-check-circle" : "fa-ban")" title="@(row.GetStatus().Equals("Inativo") ? "Ativar" : "Desativar")"></i></a>
                                        </td>
                                    </tr>
                                }
                              
                            </table>
                        }
                        else
                        {
                            <p class="alert alert-borderless">
                                Não existem registros cadastrados.
                            </p>
                        }

                        
                    </div>
                </div>
            </div>
        </div>
        <!-- END VALIDATION STATES-->
    </div>
</div>
<script type="text/javascript">
    var Inside = function () {
        var handleTable = function () {
            $('table').dataTable({

                // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
                // So when dropdowns used the scrollable div should be removed.
                //"dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

                "lengthMenu": [
                    [5, 15, 20, -1],
                    [5, 15, 20, "Todos"] // change per page values here
                ],

                // Or you can use remote translation file
                //"language": {
                //   url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese.json'
                //},

                // set the initial value
                "pageLength": 10,

                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                },
                "columnDefs": [{ // set default column settings
                    'orderable': true,
                    'targets': [0]
                }, {
                    "searchable": true,
                    "targets": [0]
                },
                    { "type": 'date-eu', "targets": [2] }
                ],
                "order": [
                    [0, "desc"]
                ] // set first column as a default sort by asc
            });
        }
        return {
            init: function () {
                handleTable();
            }
        };
    }();
</script>