Upfinancas.MVC/Controllers/EventoController.cs
using System;
using AutoMapper;
using System.Collections.Generic;
using System.Web.Mvc;
using Upfinancas.MVC.Filters;
using Upfinancas.MVC.ViewModel;
using UpFinancas.App.Interfaces;
using UpFinancas.Domain.Entities;
using Newtonsoft.Json;

namespace Upfinancas.MVC.Controllers
{
    [AutorizacaoFilter]
    public class EventoController : Controller
    {
        private readonly IEventoApp _app;
        private readonly IContaApp _contaApp;
        private readonly IFormaApp _formaApp;
        private readonly IPessoaApp _pessoaApp;
        private readonly ICategoriaApp _categoriaApp;

        public EventoController(IEventoApp app,IContaApp contaApp, IFormaApp formaApp, IPessoaApp pessoaApp,ICategoriaApp categoriaApp)
        {
            _app = app;
            _contaApp = contaApp;
            _formaApp = formaApp;
            _pessoaApp = pessoaApp;
            _categoriaApp = categoriaApp;

        }

        // GET: Conta
        public ActionResult Index()
        {
            var  usuario = (int)Session["USUARIO"];
            var eventos = _app.Listar(usuario);

            var eventoViewModel = Mapper.Map<IEnumerable<Evento>, IEnumerable<EventoViewModel>>(eventos);
            return View(eventoViewModel);
        }
        [HttpGet]
        public ActionResult Cadastrar()
        {
            try
            {
                
                var usuario = (int)Session["USUARIO"];
                var contas = _contaApp.ListarSomenteAtivas(usuario);
                var formas = _formaApp.ListarSomenteAtivas(usuario);
                var pessoas = _pessoaApp.ListarSomenteAtivas(usuario);
                var categorias = _categoriaApp.ListarSomenteAtivasPorTipo(usuario,(int)ETipoCategoria.Despesa);
                var eventoView = new EventoViewModel(contas, formas,pessoas, categorias);

                return View(eventoView);

            }
            catch(Exception e)
            {
                TempData["ERRO"] = "Erro ao buscar dados para o lançamento: " + e.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(EventoViewModel eventoView)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var evento = Mapper.Map<EventoViewModel, Evento>(eventoView);
                    _app.Salvar(evento);
                    TempData["SUCESSO"] = "Evento salvo com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    throw new Exception("Campos inválidos.");
                }
            }
            catch (Exception e)
            {
                TempData["ERRO"] = "Erro ao salvar o evento: " + e.Message;
                var usuario = (int)Session["USUARIO"];
                var contas = _contaApp.ListarSomenteAtivas(usuario);
                var formas = _formaApp.ListarSomenteAtivas(usuario);
                var pessoas = _pessoaApp.ListarSomenteAtivas(usuario);
                var categorias = _categoriaApp.ListarSomenteAtivasPorTipo(usuario, eventoView.Tipo);
                eventoView.MontarListaContas(contas, eventoView.ContaId);
                eventoView.MontarListaFormas(formas, eventoView.FormaId);
                eventoView.MontarListaPessoas(pessoas, (int)(eventoView.PessoaId!=null? eventoView.PessoaId:0));
                eventoView.MontarListaCategorias(categorias, (int)(eventoView.CategoriaId != null ? eventoView.CategoriaId : 0));
                eventoView.MontarListaTipos(eventoView.Tipo);
                return View(eventoView);
            }
        }
        [HttpGet]
        public ActionResult Editar(int eventoId)
        {
            try
            {
                var usuario = (int)Session["USUARIO"];
                var evento = _app.Buscar(usuario, eventoId);
                var eventoViewModel = Mapper.Map<Evento, EventoViewModel>(evento);
                eventoViewModel.MontarListaContas(_contaApp.ListarSomenteAtivas(usuario),eventoViewModel.ContaId);
                eventoViewModel.MontarListaFormas(_formaApp.ListarSomenteAtivas(usuario), eventoViewModel.FormaId);
                eventoViewModel.MontarListaPessoas(_pessoaApp.ListarSomenteAtivas(usuario), (int)(eventoViewModel.PessoaId != null ? eventoViewModel.PessoaId : 0));
                eventoViewModel.MontarListaCategorias(_categoriaApp.ListarSomenteAtivasPorTipo(usuario, eventoViewModel.Tipo), (int)(eventoViewModel.CategoriaId != null ? eventoViewModel.CategoriaId : 0));
                return View("Cadastrar", eventoViewModel);

            }
            catch (Exception e)
            {
                TempData["ERRO"] = "Erro ao buscar o evento: " + e.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Excluir(int eventoId)
        {
            try
            {
                var usuario = (int)Session["USUARIO"];
                _app.Excluir(eventoId, usuario);
                TempData["SUCESSO"] = "Evento removido com sucesso.";
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                TempData["ERRO"] = "Erro ao remover o evento: " + e.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public String ListarEventosPorConta(int contaId)
        {
            try
            {
                var eventos = _app.ListarPorConta((int)Session["USUARIO"],contaId);

                var contaViewModel = Mapper.Map<IEnumerable<Evento>, IEnumerable<EventoViewModel>>(eventos);
                return JsonConvert.SerializeObject(contaViewModel, Formatting.Indented);
            }
            catch (Exception e)
            {

                return "Erro: " + e.Message;
            }

        }

        [HttpGet]
        public ActionResult Transferencia()
        {
            return View("Transferencia", new TransferenciaViewModel(_contaApp.ListarSomenteAtivas((int)Session["USUARIO"])));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Transferencia(TransferenciaViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Console.Write("teste");
                    return View(viewModel);
                }
                else
                {
                    throw new Exception("Campos inválidos.");
                }
            }
            catch(Exception e)
            {
                viewModel.MontarListaContas(_contaApp.ListarSomenteAtivas((int)Session["USUARIO"]), viewModel.ContaSaidaId);
                return View(viewModel);
            }
           
        }

    }
}

Upfinancas.MVC/Controllers/UsuarioController.cs
using AutoMapper;
using System;
using System.Web.Mvc;
using Upfinancas.MVC.Filters;
using Upfinancas.MVC.ViewModel;
using UpFinancas.App.Interfaces;
using UpFinancas.Domain.Entities;

namespace Upfinancas.MVC.Controllers
{
    [AutorizacaoFilter]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioApp _app;
        public UsuarioController(IUsuarioApp app)
        {
            _app = app;
        }

        // GET: Usuario
        [HttpGet]
        public ActionResult Index()
        {
            var usuario=(int)Session["USUARIO"];
            
            var usuarioViewModel=Mapper.Map<Usuario, UsuarioViewModel>(_app.Buscar(usuario));

            return View("Alterar", usuarioViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alterar(UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var usuarioId = (int)Session["USUARIO"];
                    var usuario = Mapper.Map<UsuarioViewModel, Usuario>(usuarioViewModel);
                    var usuarioAntigo= _app.Buscar(usuarioId);
                    usuario.Id = usuarioId;
                    usuario.DataConfirmacao = usuarioAntigo.DataConfirmacao;
                    _app.Salvar(usuario);
                    TempData["SUCESSO"] = "Dados alterados com sucesso!";
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    TempData["ERRO"] = "Erro ao alterar os seus dados: " + e.Message;
                    return RedirectToAction("Index");
                }
            }
            return View();
        }

    }
}

Upfinancas.MVC/Views/Usuario/Alterar.cshtml
@model Upfinancas.MVC.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Meus dados";
}
<h3 class="page-title">
    Usuário <small>meus dados</small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index", "Usuario")">Meus dados</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            Alterar dados
        </li>
    </ul>

</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("Alterar", "Usuario", FormMethod.Post, new { @id = "form1", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)
                    <div class="portlet box grey-cascade">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa  fa-plus"></i> Alterar meus dados
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <div class="form-body form-vertical">
                                <div class="row">
                                    <div class="form-group">
                                        <label class="control-label col-md-4 col-sm-4 col-xs-12">
                                            Nome: <span class="text-danger">* </span>
                                        </label>
                                        <div class="col-md-4 col-sm-5 col-xs-11">
                                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-4 col-sm-4 col-xs-12">
                                            E-mail: <span class="text-danger">* </span>
                                        </label>
                                        <div class="col-md-4 col-sm-5 col-xs-11">
                                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-4 col-sm-4 col-xs-12">
                                            Confirme E-mail: <span class="text-danger">* </span>
                                        </label>
                                        <div class="col-md-4 col-sm-5 col-xs-11">
                                            @Html.EditorFor(model => model.ConfirmeEmail, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ConfirmeEmail, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-4 col-sm-4 col-xs-12">
                                            Senha: <span class="text-danger">* </span>
                                        </label>
                                        <div class="col-md-4 col-sm-5 col-xs-11">
                                            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", @Value = "" } })
                                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                                         </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-4 col-sm-4 col-xs-12">
                                            Confirme a senha: <span class="text-danger">* </span>
                                        </label>
                                        <div class="col-md-4 col-sm-5 col-xs-11">
                                            @Html.EditorFor(model => model.ConfirmarSenha, new { htmlAttributes = new { @class = "form-control",@Value=""} })
                                            @Html.ValidationMessageFor(model => model.ConfirmarSenha, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-12 text-center">
                                        <button type="submit" class="btn green">Salvar</button>
                                        @Html.ActionLink("Cancelar", "Index", "Evento", null, new { @class = "btn default" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>