Upfinancas.MVC/Controllers/ContaController.cs
using System;
using AutoMapper;
using System.Collections.Generic;
using System.Web.Mvc;
using Upfinancas.MVC.Filters;
using Upfinancas.MVC.ViewModel;
using UpFinancas.App.Interfaces;
using UpFinancas.Domain.Entities;
using Newtonsoft.Json;

namespace Upfinancas.MVC.Controllers
{
    [AutorizacaoFilter]
    public class ContaController : Controller
    {
        private readonly IContaApp _app;

        public ContaController(IContaApp app)
        {
            _app = app;
        }

        // GET: Conta
        public ActionResult Index()
        {
            var  usuario = (int)Session["USUARIO"];
            var contas = _app.Listar(usuario);

            var contaViewModel = Mapper.Map<IEnumerable<Conta>, IEnumerable<ContaViewModel>>(contas);
            return View(contaViewModel);
        }
        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(ContaViewModel contaView)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var conta = Mapper.Map<ContaViewModel, Conta>(contaView);
                    conta.UsuarioId = (int)Session["USUARIO"];
                    _app.Salvar(conta);
                    TempData["SUCESSO"] = "Conta salva com sucesso!";
                    return RedirectToAction("Index");

                }
                catch (Exception e)
                {
                    TempData["ERRO"] = "Erro ao salvar a conta: " + e.Message;
                    return View();
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Editar(int contaId)
        {
            try
            {
                var conta = _app.Buscar((int) Session["USUARIO"], contaId);
                var contaViewModel = Mapper.Map<Conta, ContaViewModel>(conta);
                return View("Cadastrar",contaViewModel);

            }
            catch (Exception e)
            {
                TempData["ERRO"] = "Erro ao buscar a conta: " + e.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult AlterarStatus(int contaId)
        {
            try
            {
                _app.AlterarStatus(contaId,(int)Session["USUARIO"]);
                TempData["SUCESSO"] = "Conta atualizada com sucesso!";

                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                TempData["ERRO"] = "Erro ao atualizar a conta: " + e.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public String ListarAtivas()
        {
            try
            {
                var contaViewModel = Mapper.Map<IEnumerable<Conta>, IEnumerable<ContaViewModel>>(_app.ListarSomenteAtivas((int)Session["USUARIO"]));
                return JsonConvert.SerializeObject(contaViewModel, Formatting.Indented);
            }
            catch (Exception e)
            {

                return "Erro: " + e.Message;
            }

        }
    }
}

Upfinancas.MVC/Controllers/ContasController.cs
using System.Net;
using System.Net.Http;
using System.Web.Http;
using UpFinancas.App.Interfaces;
using UpFinancas.Domain.Entities;

namespace Upfinancas.MVC.Controllers
{
    public class ContasController : ApiController
    {
        private readonly IContaApp _app;
        public ContasController(IContaApp app)
        {
            _app = app;
        }

        [HttpGet]
        [ActionName("Busca")]
        public HttpResponseMessage Buscar(int id)
        {
            return Request.CreateResponse(HttpStatusCode.OK, _app.Buscar(1, id)); 
        }

        [AcceptVerbs("POST","PUT")]
        public void Salvar(Conta conta)
        {
            
        }
    }
}

Upfinancas.MVC/Views/Conta/Cadastrar.cshtml
@model Upfinancas.MVC.ViewModel.ContaViewModel

@{
    ViewBag.Title = "Contas - Cadastrar";
}
<h3 class="page-title">Nova Conta</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="@Url.Action("Index","Conta")">Contas</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            Nova Conta
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa  fa-plus"></i> Nova Conta
                </div>
            </div>
            <div class="portlet-body form">
                @using (Html.BeginForm("Cadastrar", "Conta", FormMethod.Post, new {@id = "form1", @class = "form-horizontal"}))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-body">
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-4 col-xs-12">
                                Conta: <span class="text-danger">* </span>
                            </label>
                            <div class="col-md-4 col-sm-5 col-xs-11">
                                @Html.EditorFor(model => model.Nome, new {htmlAttributes = new {@class = "form-control"}})
                                @Html.ValidationMessageFor(model => model.Nome, "", new {@class = "text-danger"})
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4 col-sm-4 col-xs-12">
                                Conta Padrão?:
                            </label>
                            <div class="col-md-4 col-sm-5 col-xs-11">
                                @Html.CheckBoxFor(model => model.PadraoCheck, new {htmlAttributes = new {@class = "form-control"}})

                                @Html.ValidationMessageFor(model => model.PadraoCheck, "", new {@class = "text-danger"})
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn green">Salvar</button>
                                @Html.ActionLink("Volta", "Index", "Conta", null, new {@class = "btn default"})
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Upfinancas.MVC/Views/Conta/Index.cshtml
@model IEnumerable< Upfinancas.MVC.ViewModel.ContaViewModel > 
@{
    ViewBag.Title = "Contas";
}
<h3 class="page-title">
    Contas <small>cadastradas</small>
</h3>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="fa fa-home"></i>
            <a href="@Url.Action("Index","Home")">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            Contas
        </li>
    </ul>
    <div class="page-toolbar">
        <div class="btn-group pull-right">
            <a href="@Url.Action("Cadastrar","Conta")" class="btn green btn-fit-height"><i class="fa  fa-plus"></i> Novo</a>
        </div>
    </div>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN VALIDATION STATES-->
        <div class="portlet box grey-cascade">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-ticket"></i>Convênios
                </div>
            </div>
            <div class="portlet-body ">
                <div class="row">
                    <div class="col-md-12">
                        @if (Model.Count() > 0)
                        {
                            <table class="table table-striped text-center" id="table-viewer">
                                <thead>
                                <tr>
                                    <th>Código</th>
                                    <th>Conta</th>
                                    <th>Dt. Criação</th>
                                    <th>Padrão</th>
                                    <th>Saldo</th>
                                    <th>Visualizar</th>
                                    <th>Status</th>
                                </tr>
                                </thead>
                                @foreach (var row in Model)
                                {
                                    <tr>
                                        <td>
                                            @row.Id
                                        </td>
                                        <td>
                                            @row.Nome
                                        </td>
                                        <td>
                                            @row.GetDataCadastroPtBr()
                                        </td>
                                        <td>
                                            @row.GetPadrao()
                                        </td>
                                        <td class="@(row.Saldo<0?"text-danger":"")">
                                            @Html.DisplayFor(modelItem => row.Saldo)
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Editar","Conta", new { contaId = row.Id })" class="btn green btn-xs" title="Visualizar"><i class="fa fa-search"></i></a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("AlterarStatus","Conta",new { contaId = row.Id })" class="btn @(row.GetStatus().Equals("Inativo") ? "green" : "red") btn-xs"><i class="fa @(row.GetStatus().Equals("Inativo") ? "fa-check-circle" : "fa-ban")" title="@(row.GetStatus().Equals("Inativo") ? "Ativar" : "Desativar")"></i></a>
                                        </td>
                                    </tr>
                                }
                              
                            </table>
                        }
                        else
                        {
                            <p class="alert alert-borderless">
                                Não existem registros cadastrados.
                            </p>
                        }

                        
                    </div>
                </div>
            </div>
        </div>
        <!-- END VALIDATION STATES-->
    </div>
</div>
<script type="text/javascript">
    var Inside = function () {
        var handleTable = function () {
            $('table').dataTable({

                // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
                // So when dropdowns used the scrollable div should be removed.
                //"dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

                "lengthMenu": [
                    [5, 15, 20, -1],
                    [5, 15, 20, "Todos"] // change per page values here
                ],

                // Or you can use remote translation file
                //"language": {
                //   url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese.json'
                //},

                // set the initial value
                "pageLength": 10,

                "language": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    },
                    "oAria": {
                        "sSortAscending": ": Ordenar colunas de forma ascendente",
                        "sSortDescending": ": Ordenar colunas de forma descendente"
                    }
                },
                "columnDefs": [{ // set default column settings
                    'orderable': true,
                    'targets': [0]
                }, {
                    "searchable": true,
                    "targets": [0]
                },
                    { "type": 'date-eu', "targets": [2] }
                ],
                "order": [
                    [0, "desc"]
                ] // set first column as a default sort by asc
            });
        }
        return {
            init: function () {
                handleTable();
            }
        };
    }();
</script>